first_app/urls.py
from django.urls import path
from first_app import views

app_name = "first_app"

urlpatterns = [
    path('', views.index,name="index"),
    path('student_form/', views.student_form,name="student_form"),
    path('student_info/<int:student_id>/', views.student_info,name="student_info"),
    path('student_update/<int:student_id>/', views.student_update,name="student_update"),
    path('student_delete/<int:student_id>/', views.student_delete,name="student_delete"),
]

postgrecrud/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('first_app.urls')),
]

first_app/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.IntegerField()

    def __str__(self):
        return str(self.pk)+" "+self.first_name+" "+self.last_name

first_app/forms.py
from first_app import models
from django import forms




class stduent_form(forms.ModelForm):
    class Meta:
        model= models.Student
        fields = "__all__"

first_app/views.py
from django.shortcuts import render
from first_app import forms
from first_app.models import Student
# Create your views here.
def index(request):
    student_list = Student.objects.order_by('first_name')
    diction = {'title': 'Index','student_list':student_list}
    return  render(request,'first_app/index.html',context=diction)

def student_form(request):
    form = forms.stduent_form

    if request.method =="POST":
        form = forms.stduent_form(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = {'title': 'Student Form',"student_form": form}
    return  render(request,'first_app/student_form.html',context=diction)

def student_info(request,student_id):
    student_info = Student.objects.get(pk=student_id)
    diction={'student_info':student_info}
    return render(request,'first_app/student_info.html',context=diction)

def student_update(request,student_id):
    student_info = Student.objects.get(pk=student_id)
    form = forms.stduent_form(instance=student_info)
    
    if request.method =="POST":
        form = forms.stduent_form(request.POST,instance=student_info)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction={'student_form':form}
    return render(request,'first_app/student_update.html',context=diction)        

def student_delete(request,student_id):
    student = Student.objects.get(pk=student_id).delete()
    diction={'deletemessage': "Delete Done"}
    return render(request,'first_app/student_delete.html',context=diction)

templates/first_app/base.html
<!DOCTYPE html>
<html>
<head>
<title>{{ title }}</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{%  url 'first_app:index'  %}">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{%  url 'first_app:index'  %}">Index <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%  url 'first_app:student_form'  %}">Student Form</a>
            </li>
           
          </ul>
        </div>
      </nav>

{% block body_block %}

{% endblock %}


</body>
</html

templates/first_app/index.html
{% extends 'first_app/base.html' %}

{% block body_block %}

<h4>index</h4>


{% if student_list %}

<ul>
    {% for student in student_list %}
        <li> <a href="{% url 'first_app:student_info' student_id=student.id %}">{{student.first_name}} {{student.last_name}}</a>  </li>
    {% endfor %}
</ul>

{% else %}

<h4>No Student</h4>


{% endif %}

{% endblock  %}

templates/first_app/student_delete.html
{% extends 'first_app/base.html' %}

{% block body_block %}



<div class="alert alert-danger">{{deletemessage}}</div>
{% endblock  %}

templates/first_app/student_form.html
{% extends 'first_app/base.html' %}

{% block body_block %}

<h4>Student form</h4>

<form action="" method="POST">

    {{student_form.as_p}}
    {% csrf_token %}

    <input name="submit" type="submit" value="Add Student">
</form>

{% endblock  %}

templates/first_app/student_info.html
{% extends 'first_app/base.html' %}

{% block body_block %}

<h4>Info</h4>

<h6>Student Id: {{student_info.id}}</h6>
<h6>First Name: {{student_info.first_name}}</h6>
<h6>Last Name: {{student_info.last_name}}</h6>
<h6>Email: {{student_info.email}}</h6>
<h6>Phone: {{student_info.phone}}</h6>

<a href="{% url 'first_app:student_update' student_id=student_info.id %}" class="btn btn-primary">Update</a>
<a href="{% url 'first_app:student_delete' student_id=student_info.id %}" class="btn btn-primary">Delete</a>

{% endblock  %}

templates/first_app/student_update.html
{% extends 'first_app/base.html' %}

{% block body_block %}

<h4>Student Update</h4>

<form action="" method="POST">

    {{student_form.as_p}}
    {% csrf_token %}

    <input name="submit" type="submit" value="Update">
</form>

{% endblock  %}